currencies = {
    "AUD": {
        "ID": "R01010",
        "NumCode": "036",
        "CharCode": "AUD",
        "Name": "Австралийский доллар",
    },
    "AZN": {
        "ID": "R01020A",
        "NumCode": "944",
        "CharCode": "AZN",
        "Nominal": 1,
        "Name": "Азербайджанский манат",
    },
    "GBP": {
        "ID": "R01035",
        "NumCode": "826",
        "CharCode": "GBP",
        "Name": "Фунт стерлингов",
    },
    "AMD": {
        "ID": "R01060",
        "NumCode": "051",
        "CharCode": "AMD",
        "Name": "Армянских драмов",
    },
    "BYN": {
        "ID": "R01090B",
        "NumCode": "933",
        "CharCode": "BYN",
        "Name": "Белорусский рубль",
    },
    "BGN": {
        "ID": "R01100",
        "NumCode": "975",
        "CharCode": "BGN",
        "Name": "Болгарский лев",
    },
    "BRL": {
        "ID": "R01115",
        "NumCode": "986",
        "CharCode": "BRL",
        "Name": "Бразильский реал",
    },
    "HUF": {
        "ID": "R01135",
        "NumCode": "348",
        "CharCode": "HUF",
        "Name": "Венгерских форинтов",
    },
    "HKD": {
        "ID": "R01200",
        "NumCode": "344",
        "CharCode": "HKD",
        "Name": "Гонконгских долларов",
    },
    "DKK": {
        "ID": "R01215",
        "NumCode": "208",
        "CharCode": "DKK",
        "Name": "Датских крон",
    },
    "USD": {
        "ID": "R01235",
        "NumCode": "840",
        "CharCode": "USD",
        "Name": "Доллар США",
    },
    "EUR": {
        "ID": "R01239",
        "NumCode": "978",
        "CharCode": "EUR",
        "Name": "Евро",
    },
    "INR": {
        "ID": "R01270",
        "NumCode": "356",
        "CharCode": "INR",
        "Name": "Индийских рупий",
    },
    "KZT": {
        "ID": "R01335",
        "NumCode": "398",
        "CharCode": "KZT",
        "Name": "Казахстанских тенге",
    },
    "CAD": {
        "ID": "R01350",
        "NumCode": "124",
        "CharCode": "CAD",
        "Name": "Канадский доллар",
    },
    "KGS": {
        "ID": "R01370",
        "NumCode": "417",
        "CharCode": "KGS",
        "Name": "Киргизских сомов",
    },
    "CNY": {
        "ID": "R01375",
        "NumCode": "156",
        "CharCode": "CNY",
        "Name": "Китайских юаней",
    },
    "MDL": {
        "ID": "R01500",
        "NumCode": "498",
        "CharCode": "MDL",
        "Name": "Молдавских леев",
    },
    "NOK": {
        "ID": "R01535",
        "NumCode": "578",
        "CharCode": "NOK",
        "Name": "Норвежских крон",
    },
    "PLN": {
        "ID": "R01565",
        "NumCode": "985",
        "CharCode": "PLN",
        "Name": "Польский злотый",
    },
    "RON": {
        "ID": "R01585F",
        "NumCode": "946",
        "CharCode": "RON",
        "Name": "Румынский лей",
    },

    "SGD": {
        "ID": "R01625",
        "NumCode": "702",
        "CharCode": "SGD",
        "Name": "Сингапурский доллар",
    },
    "TJS": {
        "ID": "R01670",
        "NumCode": "972",
        "CharCode": "TJS",
        "Name": "Таджикских сомони",
    },
    "TRY": {
        "ID": "R01700J",
        "NumCode": "949",
        "CharCode": "TRY",
        "Name": "Турецких лир",
    },
    "TMT": {
        "ID": "R01710A",
        "NumCode": "934",
        "CharCode": "TMT",
        "Name": "Новый туркменский манат",
    },
    "UZS": {
        "ID": "R01717",
        "NumCode": "860",
        "CharCode": "UZS",
        "Name": "Узбекских сумов",
    },
    "UAH": {
        "ID": "R01720",
        "NumCode": "980",
        "CharCode": "UAH",
        "Name": "Украинских гривен",
    },
    "CZK": {
        "ID": "R01760",
        "NumCode": "203",
        "CharCode": "CZK",
        "Name": "Чешских крон",
    },
    "SEK": {
        "ID": "R01770",
        "NumCode": "752",
        "CharCode": "SEK",
        "Name": "Шведских крон",
    },
    "CHF": {
        "ID": "R01775",
        "NumCode": "756",
        "CharCode": "CHF",
        "Name": "Швейцарский франк",
    },
    "ZAR": {
        "ID": "R01810",
        "NumCode": "710",
        "CharCode": "ZAR",
        "Name": "Южноафриканских рэндов",
    },
    "KRW": {
        "ID": "R01815",
        "NumCode": "410",
        "CharCode": "KRW",
        "Name": "Вон Республики Корея",
    },
    "JPY": {
        "ID": "R01820",
        "NumCode": "392",
        "CharCode": "JPY",
        "Name": "Японских иен",
    },
    "RUB": {
        "ID": "",
        "NumCode": "1",
        "CharCode": "RU",
        "Name": "Рубль",
    }
}


